os: linux
dist: focal
language: python
jobs:
  include:
  - python: "3.7"
    env: TOXENV=py37
  - python: "3.8"
    env: TOXENV=py38
  - python: "3.9"
    env: TOXENV=py39
  - python: "3.9"
    env: TOXENV=pep8
  - python: "3.9"
    env: TOXENV=package
install: pip install tox
script: tox
notifications:
  email:
    on_success: change
    on_failure: always
    recipients:
      - peter@pakos.uk